### PR TITLE
up translate

### PR DESCRIPTION
**Pull request by Pushkin31**

### CODE REVIEW

**Comment by olljuh** [comment]
А зачем это добавили?175 строка
 formatted="false"

**Comment by Pushkin31** [comment]
> А зачем это добавили? 175 строка
> What is this? 175 string
> formatted="false"

Сейчас точно не смогу ответить
Я переводил постепенно, и все это тестил на своём тел

**Comment by olljuh** [comment]
> > А зачем это добавили? 175 строка
> > What is this? 175 string
> > formatted="false"
> 
> Вспомнил. Без этого не собралось
> Сейчас "раскурив" могу выдать такое:
> `If you added formatted=false then format specifiers(%,$ etc.) in your string resource are disabled and Formatter won't be able to recognize them. This will definitely help you. For your 2nd problem there is no exact solution but what I do is delete gen and bin folder and then clean build project. What happens is every time you build a project, android checks if there is any new resource available and adds it to R.java and only after that you can use it.`
> https://stackoverflow.com/questions/24404314/using-strings-xml-with-and-and-formatted

Но в английской и прошлых русских версиях всё работает без этого:
But in eng and previous ru versons everything was good without it:

<string name="tap_update_notification_content">An update is available for Tap, Tap (%1s to %1s)</string>

**Comment by Pushkin31** [comment]
> Но в английской и прошлых русских версиях всё работает без этого:
> But in eng and previous ru versons everything was good without it:
> 
> string name="tap_update_notification_content">An update is available for Tap, Tap (%1s to %1s)
может и работает, но не собирается... а перевод этой строчки нужен

**Comment by KieronQuinn** [comment]
Hi, thanks for the contribution. A lot of strings changed in 1.0, so if you are able to please transfer your changes to work on that version. If you'd rather not do this, reply and I'll copy them across for you - but this will leave some untranslated ones.

**Comment by Pushkin31** [comment]
Hello. I'm sorry, but I don't have time for this. When I do, I will gladly take it up at my leisure and promote it in pull requests

**Pull request closed without merging**
