### PR TITLE
Vibration turned off in DND mode

### PR DESCRIPTION
**Pull request by 4shutosh**
Fixes issue #12.
There's no vibration feedback for the taptap gesture if the DND mode is active.

### CODE REVIEW

**Comment by KieronQuinn** [comment]
I'm going to merge this in but add a setting to override it fyi, I'm one of the people who would want it to be possible to override so I'd expect there to be others

**Comment by 4shutosh** [comment]
Thank you!
I'll make a pr to add the setting in the feedback options.

**Comment by KieronQuinn** [comment]
Don't worry about it, I've got it in my branch I'm working on now

**Comment by 4shutosh** [comment]
Okay cool
I'll try working on some other issue.

**Pull request merged**
