### PR TITLE
Added Tasker Integration

### PR DESCRIPTION
**Pull request by joaomgcd**
Will create a plugin event in Tasker and allow you to add it as an action inside Tap, Tap.

Hope this helps! :)

### CODE REVIEW

**Comment by joaomgcd** [comment]
Cool! :) By the way, after I implemented this I was thinking that maybe it could simply always trigger the Tasker event by default (if the user has Tasker installed) because the user already has to explicitly use it as an event in Tasker, so there shouldn't be the need to configure it in 2 places. In this case it could simply trigger in ActionBase with

`    override fun onTrigger() {
        super.onTrigger()

        ActivityConfigTaskerEvent::class.java.requestQuery(context, TaskerEventUpdate())
    }`

What do you think? :)

**Comment by KieronQuinn** [comment]
Yeah that could work too, but my eventual intention is to allow for actions to be able to have gates on them as well, would that code allow different actions to trigger different tasks, or is it meant more as an "Event" trigger in Tasker?

**Comment by joaomgcd** [comment]
If there were different actions you could simply have an option in the Tasker configuration activity to allow the user to choose on which event to trigger. Or even have different events for different actions if you only expect to 2-3 actions max so that the plugin activity list would not get too big :)

In any case Tap, Tap could always trigger the Tasker event and then it's up to the user to configure the Tasker plugin even in any way they want to, even combining the event with other conditions in Tasker to make it trigger only when they want to.

**Comment by joaomgcd** [comment]
By the way, here's a short demo of some stuff you can do with this integration :) https://youtu.be/FHt_aCE3fss

**Comment by KieronQuinn** [comment]
Thanks for the video, much appreciated. I think I'll have to have a play around with Tasker, but what you suggested seems like a good idea regardless. I'll move the Tasker option to advanced (so that category actually has a use now rather than being a placeholder for, well, Tasker integration), add what you suggested and see what users think of it

**Comment by KieronQuinn** [comment]
@joaomgcd just a heads up, I pulled and installed a build with the changes but had to clear Tasker's data to make it show up as a plugin, not sure why

**Comment by KieronQuinn** [comment]
#32 with some more tasker changes

**Comment by joaomgcd** [comment]
Hi! Seems like you forgot to show the new actions in the UI under advanced? :) It's still showing in Utilities for me.. Thanks again!

**Comment by KieronQuinn** [comment]
Yep, looks like that got lost in the rebase somehow. Really need  to get a visual merge program on this machine to do it properly...

As the crash on older Android also doesn't appear to be fully fixed there'll probably be an alpha 0.2.1 release tomorrow.

**Pull request merged**
