### PR TITLE
Added Brazilian Portuguese (pt-BR) translation

### PR DESCRIPTION
**Pull request by rodrigoswz**

### CODE REVIEW

**Comment by KieronQuinn** [comment]
Hi, I added a load of new actions and gates in 0.2 alpha so rather than merge in a half-complete translation, please update the strings to include the new text. 

Thanks for your help!

**Comment by rodrigoswz** [comment]
I think it's done, anything just let me know

**Comment by KieronQuinn** [comment]
Thanks for your help 👍

**Comment by rodrigoswz** [comment]
Happy to help, thanks for this project! 😁

**Pull request merged**
