### PR TITLE
Update Turkish strings.xml

### PR DESCRIPTION
**Pull request by Fatih-BaKeR**

### CODE REVIEW

**Comment by KieronQuinn** [comment]
Hi, thanks for the contribution. A lot of strings changed in 1.0, so if you are able to please transfer your changes to work on that version. If you'd rather not do this, reply and I'll copy them across for you - but this will leave some untranslated ones.

**Comment by Fatih-BaKeR** [comment]
Hİ, thank you too. It would be great if you could add new english words to my existing translation. Because I do not have a computer and it is very difficult with the phone. If you don't, no problem, the translation may be missing :). Have a nice day. 

On 23 Ocak 2022 19:32, Kieron Quinn wrote:

Hi, thanks for the contribution. A lot of strings changed in 1.0, so if you are able to please transfer your changes to work on that version. If you'd rather not do this, reply and I'll copy them across for you - but this will leave some untranslated ones.


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by Kevindzu — COMMENTED** [review]
Nose

**Comment by suhail547** [comment]
Tuch

**Pull request closed without merging**
